# Generated by Django 4.0.5 on 2022-06-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_time_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing',
            new_name='bid_listing',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='creator',
            new_name='seller',
        ),
        migrations.AlterField(
            model_name='listing',
            name='st_bid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid', verbose_name='Starting bid'),
        ),
    ]
