# Generated by Django 4.0.5 on 2022-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='st_bid_amount',
            field=models.FloatField(default=1, verbose_name='Starting bid amount'),
            preserve_default=False,
        ),
    ]
