# Generated by Django 4.0.5 on 2022-06-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_active_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active',
            new_name='is_active',
        ),
    ]
